In [1]:
import numpy as np

In [2]:
a = np.random.rand(4,3)

In [3]:
a

array([[0.05643494, 0.71046996, 0.28593153],
       [0.68272573, 0.00747102, 0.02563225],
       [0.05618263, 0.9730307 , 0.632651  ],
       [0.20418051, 0.34086476, 0.02570889]])

NameError: name 'torch' is not defined

In [5]:
import torch

In [6]:
b = torch.from_numpy(a)


In [7]:
b

tensor([[0.0564, 0.7105, 0.2859],
        [0.6827, 0.0075, 0.0256],
        [0.0562, 0.9730, 0.6327],
        [0.2042, 0.3409, 0.0257]], dtype=torch.float64)

In [8]:
b.numpy()

array([[0.05643494, 0.71046996, 0.28593153],
       [0.68272573, 0.00747102, 0.02563225],
       [0.05618263, 0.9730307 , 0.632651  ],
       [0.20418051, 0.34086476, 0.02570889]])

In [10]:
b.mul_(2)

tensor([[0.1129, 1.4209, 0.5719],
        [1.3655, 0.0149, 0.0513],
        [0.1124, 1.9461, 1.2653],
        [0.4084, 0.6817, 0.0514]], dtype=torch.float64)

In [12]:
a

array([[0.11286988, 1.42093992, 0.57186307],
       [1.36545146, 0.01494204, 0.0512645 ],
       [0.11236527, 1.9460614 , 1.26530199],
       [0.40836102, 0.68172952, 0.05141778]])